# PACKAGE: MINUET WIFI SWITCH
#
# Controls whether the WiFi radio is enabled or disabled.
# Assumes that the wifi component exists and has the id 'minuet_wifi'.
#
# WiFi switch: lets you enable or disable the WiFi radio.
# The initial behavior of the WiFi switch depends on the restore mode.
#
# Variables:
#   - Set `minuet_wifi_switch_restore_mode` to configure the state of the WiFi radio
#     on power up and after a factory reset.  Use one of the following values:
#     - RESTORE_DEFAULT_OFF: Restores the WiFi switch state from persistent storage
#                              and set it to OFF by default after a factory reset.
#     - RESTORE_DEFAULT_ON:  Restores the WiFi switch state from persistent storage
#                              and set it to ON by default after a factory reset.
#     - ALWAYS_OFF:          Sets the WiFi switch state to OFF on power up.
#     - ALWAYS_ON:           Sets the WiFi switch state to ON on power up.
defaults:
  minuet_wifi_switch_restore_mode: RESTORE_DEFAULT_OFF
switch:
  - id: minuet_wifi_switch
    name: "WiFi Enable"
    icon: mdi:wifi
    platform: template
    optimistic: true
    restore_mode: ${minuet_wifi_switch_restore_mode}
    entity_category: config
    disabled_by_default: true
    setup_priority: 249 # WIFI priority minus 1
    on_turn_on:
      then:
        - logger.log:
            format: "WiFi enabled by WiFi switch"
            level: INFO
        - wifi.enable:
    on_turn_off:
      then:
        - logger.log:
            format: "WiFi disabled by WiFi switch"
            level: INFO
        - wifi.disable:
esphome:
  on_boot:
    - priority: 251 # WIFI priority plus 1
      then:
      - lambda: |-
          id(minuet_keypad_wifi_switch) = id(minuet_wifi_switch);
          id(minuet_wifi).set_enable_on_boot(id(minuet_wifi_switch).state);
